[supervisord]
nodaemon=true
user=mdm

[program:controller]
command=python -m controller.main
autostart=true
autorestart=true
stderr_logfile=/var/log/controller.err.log
stdout_logfile=/var/log/controller.out.log

[program:webhook]
command=uvicorn controller.api.webhook:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
stderr_logfile=/var/log/webhook.err.log
stdout_logfile=/var/log/webhook.out.log

[program:userapi]
command=uvicorn controller.api.main:app --host 0.0.0.0 --port 8001
autostart=true
autorestart=true
stderr_logfile=/var/log/userapi.err.log
stdout_logfile=/var/log/userapi.out.log