name: Python Code Quality

on:
  push:
    paths:
      - "mm-backend/**"
  pull_request:
    paths:
      - "mm-backend/**"

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r mm-backend/requirements.txt
      - name: Run Pylint
        run: pylint --rcfile=pylintrc mm-backend
      - name: Run Flake8
        run: flake8 mm-backend
      - name: Run Bandit
        run: bandit -r mm-backend
