// Generated by tools/gen_loading_skeletons.py. This file is safe to edit; the generator skips edited files.

import {PageSkeleton} from "@/components/layout/PageSkeleton";

export default function Loading() {
    return <PageSkeleton variant="detail"/>;
}
